import type {
  CalendarEvent,
  DemoScenario,
  LocalizedText,
  Provider,
  SourceRecord,
  TaskDefinition,
} from "./types";

export const bi = (en: string, zh: string): LocalizedText => ({ en, zh });

const sourceRecords: SourceRecord[] = [
  {
    id: "on-start",
    authority: "Ontario.ca",
    title: bi("Start a business in Ontario", "在安省创办企业"),
    jurisdiction: "Ontario",
    url: "https://www.ontario.ca/page/business/start",
    verified: "2026-09-04",
    cadence: bi("Quarterly", "每季度"),
    status: "verified",
  },
  {
    id: "on-structure",
    authority: "Ontario.ca",
    title: bi("Decide on an ownership structure", "选择企业所有权结构"),
    jurisdiction: "Ontario",
    url: "https://www.ontario.ca/page/business/start/decide-ownership-structure",
    verified: "2026-09-04",
    cadence: bi("Quarterly", "每季度"),
    status: "verified",
  },
  {
    id: "obr",
    authority: "Ontario.ca",
    title: bi("Ontario Business Registry", "安省企业注册处"),
    jurisdiction: "Ontario",
    url: "https://www.ontario.ca/page/ontario-business-registry",
    verified: "2026-09-04",
    cadence: bi("Monthly", "每月"),
    status: "verified",
  },
  {
    id: "on-register",
    authority: "Ontario.ca",
    title: bi("Register your business online", "在线注册安省企业"),
    jurisdiction: "Ontario",
    url: "https://www.ontario.ca/page/business/start/register-your-business-online",
    verified: "2026-09-04",
    cadence: bi("Monthly", "每月"),
    status: "verified",
  },
  {
    id: "business-name-search",
    authority: "Innovation, Science and Economic Development Canada",
    title: bi(
      "Choosing a business name: find out if the name is taken",
      "选择企业名称：核查名称是否已被使用",
    ),
    jurisdiction: "Canada",
    url: "https://www.canada.ca/en/services/business/start/choosing-a-business-name-2.html",
    verified: "2026-09-04",
    cadence: bi("Quarterly", "每季度"),
    status: "verified",
  },
  {
    id: "obr-profile",
    authority: "Ontario.ca",
    title: bi(
      "Setting up your Ontario Business Registry profile",
      "设置Ontario Business Registry资料",
    ),
    jurisdiction: "Ontario",
    url: "https://www.ontario.ca/page/setting-your-ontario-business-registry-profile",
    verified: "2026-09-04",
    cadence: bi("Monthly", "每月"),
    status: "verified",
  },
  {
    id: "ca-start-business",
    authority: "Government of Canada",
    title: bi("Starting a business", "创办企业"),
    jurisdiction: "Canada",
    url: "https://www.canada.ca/en/services/business/start.html",
    verified: "2026-09-04",
    cadence: bi("Quarterly", "每季度"),
    status: "verified",
  },
  {
    id: "cra-registration",
    authority: "Canada Revenue Agency",
    title: bi(
      "Business registration and program accounts",
      "企业注册及税务项目账户",
    ),
    jurisdiction: "Canada",
    url: "https://www.canada.ca/en/services/taxes/business-registration.html",
    verified: "2026-09-04",
    cadence: bi("Monthly", "每月"),
    status: "verified",
  },
  {
    id: "cra-records",
    authority: "Canada Revenue Agency",
    title: bi("Keeping records", "保存企业记录"),
    jurisdiction: "Canada",
    url: "https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/keeping-records.html",
    verified: "2026-09-04",
    cadence: bi("Quarterly", "每季度"),
    status: "verified",
  },
  {
    id: "gst",
    authority: "Canada Revenue Agency",
    title: bi("When to register for GST/HST", "何时注册GST/HST"),
    jurisdiction: "Canada",
    url: "https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/gst-hst-businesses/when-register-charge.html",
    verified: "2026-09-04",
    cadence: bi("Monthly", "每月"),
    status: "verified",
  },
  {
    id: "gst-filing",
    authority: "Canada Revenue Agency",
    title: bi(
      "GST/HST return reporting requirements and deadlines",
      "GST/HST申报要求与截止日期",
    ),
    jurisdiction: "Canada",
    url: "https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/gst-hst-businesses/file-gst-hst-return/reporting-requirements-deadlines.html",
    verified: "2026-09-04",
    cadence: bi("Monthly", "每月"),
    status: "verified",
  },
  {
    id: "payroll",
    authority: "Canada Revenue Agency",
    title: bi("Open or manage a payroll account", "开设或管理Payroll账户"),
    jurisdiction: "Canada",
    url: "https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/payroll/open-manage-payroll-account/determine-need-register.html",
    verified: "2026-09-04",
    cadence: bi("Monthly", "每月"),
    status: "verified",
  },
  {
    id: "payroll-remit",
    authority: "Canada Revenue Agency",
    title: bi(
      "Payroll remittance due dates",
      "Payroll代扣款汇缴截止日期",
    ),
    jurisdiction: "Canada",
    url: "https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/payroll/remitting-source-deductions/how-when-remit-due-dates.html",
    verified: "2026-09-04",
    cadence: bi("Monthly", "每月"),
    status: "verified",
  },
  {
    id: "carm",
    authority: "Canada Border Services Agency",
    title: bi("Register for the CARM client portal", "注册CARM客户门户"),
    jurisdiction: "Canada",
    url: "https://www.canada.ca/en/border-services-agency/services/carm/register.html",
    verified: "2026-09-04",
    cadence: bi("Quarterly", "每季度"),
    status: "verified",
  },
  {
    id: "bizpal",
    authority: "Innovation, Science and Economic Development Canada",
    title: bi("BizPaL permits and licences", "BizPaL许可与牌照查询"),
    jurisdiction: "Canada",
    url: "https://ised-isde.canada.ca/site/bizpal/en",
    verified: "2026-09-04",
    cadence: bi("Monthly", "每月"),
    status: "verified",
  },
  {
    id: "toronto-permits",
    authority: "City of Toronto",
    title: bi(
      "Business regulations, licences and permits",
      "多伦多商业监管、牌照和许可",
    ),
    jurisdiction: "Toronto",
    url: "https://www.toronto.ca/business-economy/new-businesses-startups/business-regulations/",
    verified: "2026-09-04",
    cadence: bi("Monthly", "每月"),
    status: "verified",
  },
  {
    id: "wsib",
    authority: "WSIB Ontario",
    title: bi("How to register with the WSIB", "如何注册WSIB"),
    jurisdiction: "Ontario",
    url: "https://www.wsib.ca/en/howtoregister",
    verified: "2026-09-04",
    cadence: bi("Quarterly", "每季度"),
    status: "verified",
  },
  {
    id: "workplace-posters",
    authority: "Ontario.ca",
    title: bi("Posters required in the workplace", "工作场所必须张贴的海报"),
    jurisdiction: "Ontario",
    url: "https://www.ontario.ca/page/posters-required-workplace",
    verified: "2026-09-04",
    cadence: bi("Quarterly", "每季度"),
    status: "verified",
  },
  {
    id: "on-employment-standards",
    authority: "Ontario.ca",
    title: bi(
      "Your guide to the Employment Standards Act",
      "安省《就业标准法》指南",
    ),
    jurisdiction: "Ontario",
    url: "https://www.ontario.ca/document/your-guide-employment-standards-act-0",
    verified: "2026-09-04",
    cadence: bi("Monthly", "每月"),
    status: "verified",
  },
  {
    id: "on-accessibility-business",
    authority: "Ontario.ca",
    title: bi(
      "Accessibility rules for businesses and non-profits",
      "企业和非营利组织无障碍规则",
    ),
    jurisdiction: "Ontario",
    url: "https://www.ontario.ca/page/accessibility-rules-businesses-and-non-profits",
    verified: "2026-09-04",
    cadence: bi("Quarterly", "每季度"),
    status: "verified",
  },
  {
    id: "on-small-business-safety",
    authority: "Ontario.ca",
    title: bi(
      "Health and safety for small businesses",
      "小型企业职业健康与安全",
    ),
    jurisdiction: "Ontario",
    url: "https://www.ontario.ca/page/health-and-safety-small-businesses",
    verified: "2026-09-04",
    cadence: bi("Quarterly", "每季度"),
    status: "verified",
  },
  {
    id: "t2",
    authority: "Canada Revenue Agency",
    title: bi("T2 corporation income tax return", "T2公司所得税申报"),
    jurisdiction: "Canada",
    url: "https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/corporations/corporation-income-tax-return.html",
    verified: "2026-09-04",
    cadence: bi("Monthly", "每月"),
    status: "verified",
  },
  {
    id: "t2-filing",
    authority: "Canada Revenue Agency",
    title: bi(
      "When to file a corporation income tax return",
      "公司所得税申报截止日期",
    ),
    jurisdiction: "Canada",
    url: "https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/corporations/corporation-income-tax-return/when-file-your-corporation-income-tax-return.html",
    verified: "2026-09-04",
    cadence: bi("Monthly", "每月"),
    status: "verified",
  },
  {
    id: "isc",
    authority: "Ontario.ca",
    title: bi(
      "Beneficial ownership information requirements",
      "实际控制人信息要求",
    ),
    jurisdiction: "Ontario",
    url: "https://www.ontario.ca/page/beneficial-ownership-information-requirements",
    verified: "2026-09-04",
    cadence: bi("Quarterly", "每季度"),
    status: "verified",
  },
  {
    id: "pipeda",
    authority: "Office of the Privacy Commissioner of Canada",
    title: bi("PIPEDA requirements in brief", "PIPEDA要求概览"),
    jurisdiction: "Canada",
    url: "https://www.priv.gc.ca/en/privacy-topics/privacy-laws-in-canada/the-personal-information-protection-and-electronic-documents-act-pipeda/pipeda_brief/",
    verified: "2026-09-04",
    cadence: bi("Quarterly", "每季度"),
    status: "verified",
  },
  {
    id: "casl",
    authority: "CRTC",
    title: bi("Canada's anti-spam legislation", "加拿大反垃圾邮件法"),
    jurisdiction: "Canada",
    url: "https://crtc.gc.ca/eng/internet/anti/reg.htm",
    verified: "2026-09-04",
    cadence: bi("Quarterly", "每季度"),
    status: "verified",
  },
  {
    id: "t2-balance",
    authority: "Canada Revenue Agency",
    title: bi("Corporation balance-due date", "公司税款余额到期日"),
    jurisdiction: "Canada",
    url: "https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/corporations/corporation-payments/paying-your-balance-corporation-tax/balance-day.html",
    verified: "2026-09-04",
    cadence: bi("Monthly", "每月"),
    status: "verified",
  },
];

export const sources: SourceRecord[] = sourceRecords.map((source) => ({
  ...source,
  verified: "2026-09-04",
}));

const defaultDueByPhase: Record<TaskDefinition["phase"], LocalizedText> = {
  plan: bi("Before the next registration step", "进入下一注册步骤前"),
  register: bi("At the relevant registration milestone", "在相关注册里程碑时"),
  set_up: bi("Before the related activity begins", "相关经营活动开始前"),
  operate: bi("Before launch and after material changes", "启动前及重大变化后"),
  comply: bi("Confirm the assigned or statutory deadline", "确认分配或法定截止日"),
};

const workflowMetadata: Record<
  string,
  Pick<TaskDefinition, "dependsOn" | "due" | "workflowRisk">
> = {
  "name-search": {
    dependsOn: ["choose-structure"],
    due: bi("Before submitting a named registration", "提交具名注册前"),
    workflowRisk: "low",
  },
  "ontario-registration": {
    dependsOn: ["choose-structure"],
    due: bi("Before operating under a registrable name or structure", "使用需注册的名称或结构经营前"),
    workflowRisk: "high",
  },
  "registration-review": {
    dependsOn: ["choose-structure"],
    due: bi(
      "Before the next Ontario registry or CRA account step",
      "进行下一项安省注册处或CRA账户操作前",
    ),
    workflowRisk: "high",
  },
  "obr-access": {
    dependsOn: ["ontario-registration"],
    due: bi("Before the next Ontario registry transaction", "下一次安省注册处交易前"),
    workflowRisk: "medium",
  },
  "corporate-records": {
    dependsOn: ["ontario-registration"],
    due: bi("Promptly after incorporation", "公司成立后尽快"),
    workflowRisk: "high",
  },
  "bn-accounts": {
    dependsOn: ["ontario-registration"],
    due: bi("Before the relevant CRA program activity", "相关CRA项目活动开始前"),
    workflowRisk: "high",
  },
  "payroll-account": {
    dependsOn: ["bn-accounts"],
    due: bi("Before the first payroll remittance is due", "首次Payroll汇缴到期前"),
    workflowRisk: "high",
  },
  "import-export": {
    dependsOn: ["bn-accounts"],
    due: bi("Before importing commercial goods", "进口商业货物前"),
    workflowRisk: "high",
  },
  "annual-return": {
    dependsOn: ["corporate-records"],
    due: bi("Within six months after the fiscal year-end", "财年结束后六个月内"),
    workflowRisk: "high",
  },
  "t2-return": {
    dependsOn: ["corporate-records"],
    due: bi("Within six months after the tax year-end", "税年结束后六个月内"),
    workflowRisk: "high",
  },
  "t2-balance": {
    dependsOn: ["corporate-records"],
    due: bi("Usually two or three months after tax year-end; confirm", "通常为税年结束后两或三个月；需确认"),
    workflowRisk: "high",
  },
  "gst-return": {
    dependsOn: ["gst-decision"],
    due: bi("CRA-assigned filing cycle, only after registration", "仅在注册后按CRA分配的申报周期"),
    workflowRisk: "high",
  },
  "payroll-remittance": {
    dependsOn: ["payroll-account"],
    due: bi("CRA-assigned remitter frequency", "按CRA分配的汇缴频率"),
    workflowRisk: "high",
  },
  "isc-review": {
    dependsOn: ["corporate-records"],
    due: bi("At least annually and after known changes", "至少每年一次，并在获悉变更后"),
    workflowRisk: "high",
  },
};

const compactTask = (
  id: string,
  number: string,
  phase: TaskDefinition["phase"],
  titleEn: string,
  titleZh: string,
  summaryEn: string,
  summaryZh: string,
  sourceIds: string[],
  tags: string[],
): TaskDefinition => ({
  id,
  number,
  phase,
  title: bi(titleEn, titleZh),
  shortTitle: bi(titleEn, titleZh),
  summary: bi(summaryEn, summaryZh),
  sourceIds,
  full: false,
  tags,
  due: workflowMetadata[id]?.due ?? defaultDueByPhase[phase],
  dependsOn: workflowMetadata[id]?.dependsOn ?? [],
  workflowRisk: workflowMetadata[id]?.workflowRisk ?? "medium",
});

const detailedTask = (
  task: TaskDefinition,
  why: LocalizedText,
  materials: LocalizedText[],
  cost: LocalizedText,
  timing: LocalizedText,
  officialUrl: string,
): TaskDefinition => ({
  ...task,
  why,
  materials,
  cost,
  timing,
  officialUrl,
  full: true,
});

export const tasks: TaskDefinition[] = [
  detailedTask(
    compactTask(
      "choose-structure",
      "01",
      "plan",
      "Choose a business structure",
      "选择企业结构",
      "Compare sole proprietorship and corporation against ownership, liability, tax administration and growth needs.",
      "结合所有权、责任、税务管理及发展需要，对比个体经营和公司结构。",
      ["on-structure"],
      ["all", "planning"],
    ),
    bi(
      "Structure affects registration, liability, tax accounts and ongoing filings. The workspace explains trade-offs but does not make a legal choice for you.",
      "企业结构会影响注册、责任、税务账户和持续申报。工作台解释差异，但不会替您作出法律选择。",
    ),
    [
      bi("Owner and co-founder list", "业主及联合创始人列表"),
      bi("Expected activities and locations", "预计经营活动和地点"),
      bi("12-month revenue and hiring plan", "未来12个月收入和招聘计划"),
    ],
    bi("No government fee to compare structures", "比较结构无需政府费用"),
    bi(
      "10–20 minutes to review; seek advice for complex ownership",
      "查看约10–20分钟；复杂所有权建议咨询专业人士",
    ),
    "https://www.ontario.ca/page/business/start/decide-ownership-structure",
  ),
  detailedTask(
    compactTask(
      "name-search",
      "02",
      "plan",
      "Check your proposed name",
      "核查拟用企业名称",
      "Run a basic web, registry, trademark and domain check before committing to a name.",
      "确定名称前，完成网络、注册处、商标和域名的基础核查。",
      ["business-name-search", "on-register"],
      ["registration", "brand"],
    ),
    bi(
      "Ontario business-name registration is distinct from trademark protection and does not create exclusive federal rights to the name. An Ontario business corporation using a number name does not need the Ontario-biased or weighted Nuans report required for a word name.",
      "安省企业名称注册不同于商标保护，也不会产生对该名称的联邦专有权。安省商业公司使用编号名称时，无需提交文字名称所需的Ontario-biased或weighted Nuans报告。",
    ),
    [
      bi("Two or three name options", "两到三个备选名称"),
      bi("Business activity description", "经营活动说明"),
      bi("Desired domains", "希望使用的域名"),
    ],
    bi(
      "Searches may be free; a required name report has a separate fee",
      "部分搜索免费；如需名称报告则另有费用",
    ),
    bi("15–45 minutes for initial screening", "初步筛选约15–45分钟"),
    "https://www.canada.ca/en/services/business/start/choosing-a-business-name-2.html",
  ),
  detailedTask(
    compactTask(
      "ontario-registration",
      "03",
      "register",
      "Register with Ontario and record the Ontario BIN",
      "完成安省注册并记录Ontario BIN",
      "Prepare for the appropriate Ontario Business Registry transaction. The Ontario Business Identification Number (BIN) is different from the CRA Business Number (BN).",
      "准备相应的Ontario Business Registry交易。安省Business Identification Number（BIN）不同于CRA Business Number（BN）。",
      ["on-structure", "on-register", "obr"],
      ["registration", "ontario"],
    ),
    bi(
      "Most Ontario corporations and business names use the Ontario Business Registry. Some sole proprietors using only their legal name may not need a business-name registration. An Ontario BIN identifies a provincial registration; it is not a CRA BN.",
      "多数安省公司和企业名称通过Ontario Business Registry办理。仅使用本人法定姓名经营的部分个体经营者可能无需注册企业名称。Ontario BIN用于识别省级注册，并不是CRA BN。",
    ),
    [
      bi("Structure and name decision", "结构和名称决定"),
      bi("Ontario address and contact details", "安省地址和联系信息"),
      bi("Director or owner details", "董事或业主信息"),
    ],
    bi(
      "Official fees vary by transaction. Check the dated Ontario fee table before filing.",
      "官方费用因交易而异。提交前请查看注明日期的安省费用表。",
    ),
    bi(
      "Often completed online; processing varies by transaction",
      "通常可在线完成；处理时间因交易类型而异",
    ),
    "https://www.ontario.ca/page/ontario-business-registry",
  ),
  compactTask(
    "registration-review",
    "03R",
    "register",
    "Verify an existing Ontario registration",
    "核验现有安省注册",
    "Confirm that the registration is active and record only the existence or recovery status of the Ontario BIN and Company Key. Do not enter either value in this demo.",
    "确认注册状态有效，并仅记录Ontario BIN及Company Key是否已取得或可找回；请勿在本演示中输入这些具体值。",
    ["on-register", "obr"],
    ["registration", "ontario", "review"],
  ),
  detailedTask(
    compactTask(
      "obr-access",
      "04",
      "register",
      "Set up Ontario registry access",
      "设置安省注册服务访问",
      "Understand Ontario.ca Login, Ontario Business Account and Company Key requirements before opening the registry.",
      "在进入注册处前，了解Ontario.ca Login、Ontario Business Account及Company Key要求。",
      ["obr-profile", "obr"],
      ["registration", "access"],
    ),
    bi(
      "The official setup requires a Company Key, an Ontario.ca Login and an Ontario Business Account. The Company Key is confidential and links an existing entity to its registry profile.",
      "官方设置需要Company Key、Ontario.ca Login及Ontario Business Account。Company Key属于机密信息，用于将现有实体关联到其注册处资料。",
    ),
    [
      bi("Your own email address", "您自己的电子邮箱"),
      bi("Existing Company Key, if applicable", "已有Company Key（如适用）"),
      bi("Legal entity details", "法律实体信息"),
    ],
    bi(
      "No Launchpad fee; official transaction fees may apply",
      "Launchpad不收费；官方交易可能产生费用",
    ),
    bi("Allow extra time for access recovery", "如需恢复访问，请预留额外时间"),
    "https://www.ontario.ca/page/setting-your-ontario-business-registry-profile",
  ),
  detailedTask(
    compactTask(
      "corporate-records",
      "05",
      "register",
      "Set up corporate records",
      "建立公司记录",
      "Organize articles, registers, resolutions and ownership records after incorporation.",
      "公司成立后，整理章程、登记册、决议及所有权记录。",
      ["obr", "isc"],
      ["corporation", "records"],
    ),
    bi(
      "Incorporation is not the end of corporate housekeeping. Accurate records support banking, tax, ownership changes and annual compliance.",
      "公司成立并不代表公司治理工作结束。准确记录有助于银行、税务、所有权变更和年度合规。",
    ),
    [
      bi("Articles and certificate", "公司章程和成立证明"),
      bi("Director and officer details", "董事及高级职员信息"),
      bi("Share and significant-control information", "股份及实际控制信息"),
    ],
    bi(
      "No government fee to organize records; professional support is optional",
      "整理记录无政府费用；专业支持为可选",
    ),
    bi("Set up promptly after incorporation", "建议成立后尽快建立"),
    "https://www.ontario.ca/page/beneficial-ownership-information-requirements",
  ),
  detailedTask(
    compactTask(
      "bn-accounts",
      "06",
      "set_up",
      "Confirm your CRA BN and tax accounts",
      "确认CRA BN及税务账户",
      "Identify whether you need a CRA Business Number and corporation income tax, GST/HST or payroll accounts. Import-export setup is tracked separately through CBSA CARM/RM.",
      "判断是否需要CRA Business Number及公司所得税、GST/HST或Payroll账户。进出口设置通过CBSA CARM/RM单独跟踪。",
      ["cra-registration"],
      ["tax", "cra"],
    ),
    bi(
      "A nine-digit CRA BN identifies a business for federal program accounts and is different from an Ontario BIN. Each tax account serves a different obligation; CBSA manages CARM and the RM import-export account separately.",
      "九位CRA BN用于识别联邦项目账户，并不同于Ontario BIN。各税务账户对应不同义务；CARM及RM进出口账户由CBSA单独管理。",
    ),
    [
      bi("Legal business information", "企业法定信息"),
      bi("Registration or incorporation number", "注册或公司编号"),
      bi("Program account needs", "所需项目账户"),
    ],
    bi("CRA registration is generally free", "CRA注册通常免费"),
    bi(
      "Online eligibility and processing vary",
      "在线资格和处理时间因情况而异",
    ),
    "https://www.canada.ca/en/services/taxes/business-registration.html",
  ),
  detailedTask(
    compactTask(
      "gst-decision",
      "07",
      "set_up",
      "Make the GST/HST registration decision",
      "判断是否注册GST/HST",
      "Track taxable worldwide supplies and distinguish mandatory registration from a voluntary choice.",
      "跟踪全球应税销售额，并区分强制注册和自愿注册。",
      ["gst"],
      ["tax", "gst"],
    ),
    bi(
      "The general small-supplier threshold is not a single annual-date test. Timing differs if you exceed CAD 30,000 in one calendar quarter versus over four consecutive quarters.",
      "一般小供应商门槛并非仅按一个年度日期判断。在单一季度超过CAD 30,000与连续四个季度累计超过时，生效时间不同。",
    ),
    [
      bi("Taxable supplies by calendar quarter", "按日历季度统计的应税销售额"),
      bi("Associated-person information, if relevant", "关联方信息（如相关）"),
      bi("Expected input tax credits", "预计可抵扣进项税额"),
    ],
    bi(
      "CRA registration is free; collection and filing duties follow registration",
      "CRA注册免费；注册后将产生征收和申报义务",
    ),
    bi(
      "Review now and after every material revenue change",
      "现在评估，并在收入发生重大变化后重新评估",
    ),
    "https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/gst-hst-businesses/when-register-charge.html",
  ),
  detailedTask(
    compactTask(
      "payroll-account",
      "08",
      "set_up",
      "Open a payroll account",
      "开设Payroll账户",
      "Prepare a CRA payroll program account before the first remittance obligation.",
      "在首次代扣款汇缴义务发生前，准备CRA Payroll项目账户。",
      ["payroll"],
      ["hiring", "payroll"],
    ),
    bi(
      "Hiring creates payroll withholding, remittance and reporting obligations. The due date depends on the remitter type assigned by CRA.",
      "招聘会产生工资代扣、汇缴和申报义务；截止日期取决于CRA分配的汇缴类别。",
    ),
    [
      bi("BN and legal business details", "BN及企业法定信息"),
      bi("First pay date and pay frequency", "首次发薪日期和发薪频率"),
      bi("Estimated annual payroll", "预计年度工资总额"),
    ],
    bi("CRA account setup is generally free", "CRA账户开设通常免费"),
    bi("Complete before the first remittance is due", "在首次汇缴截止日前完成"),
    "https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/payroll/open-manage-payroll-account/determine-need-register.html",
  ),
  detailedTask(
    compactTask(
      "import-export",
      "09",
      "set_up",
      "Prepare for commercial importing",
      "准备商业进口",
      "Confirm BN9, CARM access and an import-export program account before importing commercial goods.",
      "进口商业货物前，确认BN9、CARM访问及进出口项目账户。",
      ["carm", "cra-registration"],
      ["ecommerce", "import"],
    ),
    bi(
      "Commercial imports use CBSA's CARM system. Business registration and authority should remain under the importer's control.",
      "商业进口使用CBSA的CARM系统；企业注册和授权应由进口商自行控制。",
    ),
    [
      bi("BN9", "BN9"),
      bi("Importer contact and address", "进口商联系人和地址"),
      bi("Goods and customs-broker plan", "货物及报关代理计划"),
    ],
    bi(
      "Account registration is free; duties, taxes and broker fees may apply",
      "账户注册免费；可能产生关税、税款和报关费用",
    ),
    bi("Set up before the first commercial shipment", "首次商业发货前设置"),
    "https://www.canada.ca/en/border-services-agency/services/carm/register.html",
  ),
  detailedTask(
    compactTask(
      "permit-scan",
      "10",
      "set_up",
      "Run a permit and licence scan",
      "查询许可和牌照",
      "Use location and activity details with BizPaL, then save the result as a tracked checklist.",
      "使用地点和经营活动信息通过BizPaL查询，并将结果保存为可跟踪清单。",
      ["bizpal"],
      ["permits", "all"],
    ),
    bi(
      "Requirements can span federal, provincial and municipal governments. BizPaL results are a starting point and may not be exhaustive.",
      "要求可能横跨联邦、省和市三级政府。BizPaL结果是起点，但不一定穷尽全部要求。",
    ),
    [
      bi("Exact operating address", "准确经营地址"),
      bi("Plain-language activity description", "通俗的经营活动说明"),
      bi("Products and customer interaction", "产品及客户互动方式"),
    ],
    bi(
      "BizPaL search is free; permit fees vary",
      "BizPaL查询免费；许可费用因类别而异",
    ),
    bi("10–20 minutes for the first scan", "首次查询约10–20分钟"),
    "https://ised-isde.canada.ca/site/bizpal/en",
  ),
  detailedTask(
    compactTask(
      "toronto-check",
      "11",
      "set_up",
      "Check Toronto requirements",
      "核查多伦多市级要求",
      "Review zoning, municipal licensing and home-based business considerations for a Toronto location.",
      "针对多伦多经营地点，检查分区、市级牌照及居家经营注意事项。",
      ["toronto-permits"],
      ["permits", "toronto"],
    ),
    bi(
      "Municipal requirements depend on both activity and address. Confirm before signing a lease or opening to the public.",
      "市级要求同时取决于经营活动和地址。签署租约或向公众营业前应先确认。",
    ),
    [
      bi("Operating address", "经营地址"),
      bi("Activity and premises details", "经营活动及场所详情"),
      bi(
        "Any signage, food or public-access plans",
        "招牌、食品或公众到访计划",
      ),
    ],
    bi(
      "Research is free; application and inspection fees vary",
      "查询免费；申请及检查费用因类别而异",
    ),
    bi(
      "Complete before lease commitment where possible",
      "如可能，应在签署租约前完成",
    ),
    "https://www.toronto.ca/business-economy/new-businesses-startups/business-regulations/",
  ),
  compactTask(
    "business-banking",
    "12",
    "set_up",
    "Optionally prepare for business banking",
    "按需准备企业银行服务",
    "This is an optional recordkeeping and provider-comparison step. Eligibility, documents, identity checks, fees and timing are specific to each financial institution; confirm them directly with the provider.",
    "这是可选的记录管理和服务商比较步骤。资格、所需文件、身份核验、费用及时长均由各金融机构自行规定，请直接向服务商确认。",
    ["cra-records"],
    ["banking", "operations", "optional"],
  ),
  detailedTask(
    compactTask(
      "accounting-stack",
      "13",
      "operate",
      "Set up bookkeeping",
      "建立记账体系",
      "Choose a chart of accounts, receipt workflow and regular reconciliation rhythm.",
      "选择会计科目、票据流程及定期对账节奏。",
      ["cra-records"],
      ["accounting", "operations"],
    ),
    bi(
      "CRA requires accounting and financial records to be organized and detailed enough to determine tax obligations and entitlements. Records may be kept on paper, electronically or in both formats.",
      "CRA要求会计及财务记录保持有序，并具有足够细节以确定税务义务和权益。记录可以纸质、电子或两种格式保存。",
    ),
    [
      bi("Business bank and payment feeds", "企业银行及支付流水"),
      bi("Expense categories", "费用类别"),
      bi("Record retention owner", "记录保管负责人"),
    ],
    bi(
      "Software and bookkeeping support vary by provider",
      "软件及记账支持费用因服务商而异",
    ),
    bi("Set up before transaction volume grows", "建议在交易量增长前建立"),
    "https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/keeping-records.html",
  ),
  detailedTask(
    compactTask(
      "insurance-review",
      "14",
      "operate",
      "Review business insurance needs",
      "评估企业保险需要",
      "Describe activities, revenue, premises and staffing for a licensed broker or insurer.",
      "向持牌经纪或保险公司说明经营活动、收入、场所和人员情况。",
      ["on-start"],
      ["insurance", "risk"],
    ),
    bi(
      "Coverage depends on facts and underwriting. Launchpad organizes questions but does not recommend coverage or bind a policy.",
      "保险范围取决于具体情况和核保。Launchpad帮助整理问题，但不推荐保险范围，也不承保。",
    ),
    [
      bi("Business activity and revenue", "经营活动和收入"),
      bi("Premises, equipment and customer data", "场所、设备及客户数据"),
      bi(
        "Claims history, if requested by the provider",
        "理赔历史（如服务商要求）",
      ),
    ],
    bi(
      "Quotes and premiums vary; partner compensation must be disclosed",
      "报价及保费因情况而异；合作方报酬必须披露",
    ),
    bi(
      "Review before contracts or operations create exposure",
      "建议在合同或经营活动产生风险前评估",
    ),
    "https://www.ontario.ca/page/business/start",
  ),
  detailedTask(
    compactTask(
      "privacy-casl",
      "15",
      "operate",
      "Set a privacy and consent baseline",
      "建立隐私与同意基础",
      "Map customer data and separate operational communications from promotional consent.",
      "梳理客户数据，并将运营通知与营销同意分开。",
      ["pipeda", "casl"],
      ["privacy", "marketing"],
    ),
    bi(
      "Most Ontario private-sector businesses must consider PIPEDA, while commercial electronic messages generally require CASL controls.",
      "安省多数私营企业需要考虑PIPEDA；商业电子信息通常需要遵循CASL控制要求。",
    ),
    [
      bi("Data inventory and business purposes", "数据清单及业务目的"),
      bi("Vendor and cross-border processing list", "供应商及跨境处理清单"),
      bi("Consent and unsubscribe records", "同意及退订记录"),
    ],
    bi(
      "Internal review is free; professional advice may carry a fee",
      "内部检查免费；专业咨询可能收费",
    ),
    bi(
      "Complete before collecting customer data or sending campaigns",
      "收集客户数据或发送营销信息前完成",
    ),
    "https://www.priv.gc.ca/en/privacy-topics/privacy-laws-in-canada/the-personal-information-protection-and-electronic-documents-act-pipeda/pipeda_brief/",
  ),
  compactTask(
    "client-contracts",
    "16",
    "operate",
    "Prepare client or supplier contracts",
    "准备客户或供应商合同",
    "Document scope, price, payment, privacy and responsibility; use professional review when risk is material.",
    "记录范围、价格、付款、隐私和责任；风险重大时寻求专业审查。",
    ["on-start"],
    ["contracts"],
  ),
  compactTask(
    "payments",
    "17",
    "operate",
    "Choose payment methods",
    "选择收款方式",
    "Compare settlement time, fees, chargebacks, currencies and bookkeeping fit.",
    "比较结算时间、费用、拒付、币种及记账匹配度。",
    ["on-start"],
    ["payments"],
  ),
  compactTask(
    "record-policy",
    "18",
    "operate",
    "Create a recordkeeping policy",
    "建立记录保管制度",
    "Document who maintains organized income, expense, GST/HST and payroll records, in which format, and which CRA retention periods apply.",
    "记录由谁维护有序的收入、支出、GST/HST及Payroll资料、采用何种格式，以及适用哪些CRA保留期限。",
    ["cra-records"],
    ["accounting"],
  ),
  compactTask(
    "quarterly-review",
    "19",
    "operate",
    "Schedule a quarterly obligation review",
    "安排季度义务复核",
    "Recheck revenue, employees, activities, locations and registrations after material changes.",
    "在发生重大变化后，重新核查收入、员工、活动、地点和注册情况。",
    ["on-start"],
    ["review"],
  ),
  compactTask(
    "hiring-readiness",
    "20",
    "operate",
    "Prepare to hire the first employee",
    "准备招聘首位员工",
    "Sequence payroll, WSIB, employment documents, posters and workplace policies before the start date.",
    "在入职日前依次完成Payroll、WSIB、雇佣文件、海报和工作场所政策。",
    ["payroll", "wsib", "workplace-posters"],
    ["hiring"],
  ),
  compactTask(
    "wsib",
    "21",
    "operate",
    "Check and complete WSIB registration",
    "核查并完成WSIB注册",
    "Use the official questionnaire and registration path; industry and worker status can affect the result.",
    "使用官方问卷和注册路径；行业和工作人员身份会影响判断结果。",
    ["wsib"],
    ["hiring", "wsib"],
  ),
  compactTask(
    "posters",
    "22",
    "operate",
    "Post required workplace information",
    "张贴所需工作场所信息",
    "Download current Ontario posters and provide them in the required format.",
    "下载最新版安省工作场所海报，并按要求提供。",
    ["workplace-posters"],
    ["hiring"],
  ),
  compactTask(
    "employment-baseline",
    "23",
    "operate",
    "Set an employment standards baseline",
    "建立雇佣标准基础",
    "Use Ontario's official guides to determine which pay, hours, vacation, leave, accessibility and health-and-safety duties apply to your workforce and workplace.",
    "使用安省官方指南，根据员工及工作场所情况判断适用的工资、工时、休假、无障碍及职业健康安全义务。",
    [
      "on-employment-standards",
      "on-accessibility-business",
      "on-small-business-safety",
    ],
    ["hiring"],
  ),
  compactTask(
    "annual-return",
    "24",
    "comply",
    "File the Ontario corporate annual return",
    "提交安省公司年度申报",
    "Track the corporate registry filing separately from tax returns.",
    "将公司注册处年度申报与税务申报分开跟踪。",
    ["obr"],
    ["corporation", "annual"],
  ),
  compactTask(
    "t2-return",
    "25",
    "comply",
    "Prepare the T2 corporation tax return",
    "准备T2公司所得税申报",
    "A corporation generally files a T2 for each tax year, even when no tax is payable.",
    "公司通常每个税年都需提交T2，即使没有应纳税额。",
    ["t2", "t2-filing"],
    ["corporation", "tax"],
  ),
  compactTask(
    "t2-balance",
    "25B",
    "comply",
    "Review the corporation tax balance due",
    "复核公司税款余额到期日",
    "Track the corporation tax balance separately from the T2 filing deadline; the timing can be earlier.",
    "将公司税款余额到期日与T2申报截止日分开跟踪；付款时间可能更早。",
    ["t2-balance"],
    ["corporation", "tax"],
  ),
  compactTask(
    "gst-return",
    "26",
    "comply",
    "Prepare GST/HST returns",
    "准备GST/HST申报",
    "After registration, use the CRA-assigned reporting period and account deadlines, and file a return for every reporting period, including a nil return when required.",
    "注册后，按CRA分配的申报周期及账户截止日期办理，并为每个申报期提交申报；在需要时也须提交零申报。",
    ["gst-filing"],
    ["tax", "gst"],
  ),
  compactTask(
    "payroll-remittance",
    "27",
    "comply",
    "Remit payroll deductions",
    "汇缴工资代扣款",
    "Use the CRA-assigned remitter frequency rather than a generic date.",
    "应依据CRA分配的汇缴频率，而非使用统一日期。",
    ["payroll-remit"],
    ["payroll", "tax"],
  ),
  compactTask(
    "isc-review",
    "28",
    "comply",
    "Review individuals with significant control",
    "复核实际控制人信息",
    "Ontario private corporations keep and review their ISC information at least annually and after changes.",
    "安省私人公司应至少每年并在发生变更后保存和复核ISC信息。",
    ["isc"],
    ["corporation", "governance"],
  ),
  compactTask(
    "name-renewal",
    "29",
    "comply",
    "Track business-name renewal",
    "跟踪企业名称续期",
    "Keep the registration expiry visible and confirm the current renewal path before it is due.",
    "持续显示注册到期时间，并在到期前确认现行续期流程。",
    ["obr"],
    ["registration", "renewal"],
  ),
  compactTask(
    "renewal-review",
    "30",
    "comply",
    "Review permits, insurance and domains",
    "复核许可、保险和域名",
    "Maintain a single renewal view while each item remains with its issuing provider.",
    "在统一视图中维护续期信息，但各项目仍由原签发方办理。",
    ["bizpal", "toronto-permits"],
    ["renewal"],
  ),
];

const plan = (
  entries: Array<[string, DemoScenario["tasks"][number]["kind"]]>,
) => entries.map(([id, kind]) => ({ id, kind }));

export const scenarios: DemoScenario[] = [
  {
    id: "toronto-consultant",
    number: "01",
    title: bi("Toronto digital consultant", "多伦多数字咨询顾问"),
    descriptor: bi(
      "Sole proprietor · no employees · under CAD 30k",
      "个体经营 · 无员工 · 低于CAD 30k",
    ),
    outcome: bi(
      "A lean path from structure and name checks to recordkeeping, permits and privacy basics.",
      "从结构和名称核查，到记账、许可及隐私基础的轻量路径。",
    ),
    badge: bi("Fast-start path", "快速启动路径"),
    accent: "blue",
    profile: {
      stage: "planning",
      city: "Toronto",
      industry: "services",
      structure: "sole_prop",
      employees: "none",
      revenue: "under_30k",
      imports: false,
      crossProvince: false,
      complexResidency: false,
    },
    tasks: plan([
      ["choose-structure", "mandatory"],
      ["name-search", "conditional"],
      ["ontario-registration", "conditional"],
      ["permit-scan", "mandatory"],
      ["gst-decision", "mandatory"],
      ["accounting-stack", "mandatory"],
      ["privacy-casl", "mandatory"],
      ["record-policy", "mandatory"],
      ["quarterly-review", "mandatory"],
      ["insurance-review", "optional"],
      ["toronto-check", "conditional"],
      ["business-banking", "optional"],
      ["name-renewal", "conditional"],
      ["annual-return", "not_applicable"],
      ["t2-return", "not_applicable"],
      ["t2-balance", "not_applicable"],
      ["isc-review", "not_applicable"],
      ["import-export", "not_applicable"],
      ["payroll-account", "not_applicable"],
      ["hiring-readiness", "not_applicable"],
      ["payroll-remittance", "not_applicable"],
    ]),
  },
  {
    id: "service-corporation",
    number: "02",
    title: bi("Two-founder service corporation", "两位创始人的服务型公司"),
    descriptor: bi(
      "Ontario corporation · services · no employees yet",
      "安省公司 · 服务业 · 暂无员工",
    ),
    outcome: bi(
      "A governance-first path through incorporation, corporate records, CRA accounts and annual compliance.",
      "以治理为先，覆盖公司成立、公司记录、CRA账户及年度合规。",
    ),
    badge: bi("Corporate path", "公司路径"),
    accent: "gold",
    profile: {
      stage: "planning",
      city: "Ontario",
      industry: "services",
      structure: "corporation",
      employees: "none",
      revenue: "under_30k",
      imports: false,
      crossProvince: false,
      complexResidency: false,
    },
    tasks: plan([
      ["choose-structure", "mandatory"],
      ["name-search", "mandatory"],
      ["ontario-registration", "mandatory"],
      ["permit-scan", "mandatory"],
      ["gst-decision", "mandatory"],
      ["accounting-stack", "mandatory"],
      ["privacy-casl", "mandatory"],
      ["record-policy", "mandatory"],
      ["quarterly-review", "mandatory"],
      ["insurance-review", "optional"],
      ["obr-access", "mandatory"],
      ["corporate-records", "mandatory"],
      ["bn-accounts", "mandatory"],
      ["business-banking", "conditional"],
      ["annual-return", "mandatory"],
      ["t2-return", "mandatory"],
      ["t2-balance", "mandatory"],
      ["isc-review", "mandatory"],
      ["import-export", "not_applicable"],
      ["payroll-account", "not_applicable"],
      ["hiring-readiness", "not_applicable"],
      ["payroll-remittance", "not_applicable"],
    ]),
  },
  {
    id: "ecommerce-growth",
    number: "03",
    title: bi("E-commerce growth company", "成长型电商公司"),
    descriptor: bi(
      "Ontario corporation · near GST/HST threshold · importing",
      "安省公司 · 接近GST/HST门槛 · 进口",
    ),
    outcome: bi(
      "A revenue-aware route for GST/HST, CARM, payments, bookkeeping and customer-data controls.",
      "围绕收入变化，编排GST/HST、CARM、支付、记账及客户数据控制。",
    ),
    badge: bi("Revenue trigger", "收入触发路径"),
    accent: "teal",
    profile: {
      stage: "registered",
      city: "Ontario",
      industry: "ecommerce",
      structure: "corporation",
      employees: "none",
      revenue: "near_30k",
      imports: true,
      crossProvince: false,
      complexResidency: false,
    },
    tasks: plan([
      ["registration-review", "mandatory"],
      ["permit-scan", "mandatory"],
      ["gst-decision", "mandatory"],
      ["accounting-stack", "mandatory"],
      ["privacy-casl", "conditional"],
      ["record-policy", "conditional"],
      ["quarterly-review", "optional"],
      ["insurance-review", "optional"],
      ["obr-access", "mandatory"],
      ["corporate-records", "mandatory"],
      ["bn-accounts", "mandatory"],
      ["business-banking", "conditional"],
      ["annual-return", "mandatory"],
      ["t2-return", "mandatory"],
      ["t2-balance", "mandatory"],
      ["isc-review", "mandatory"],
      ["gst-return", "conditional"],
      ["payments", "mandatory"],
      ["import-export", "mandatory"],
      ["payroll-account", "not_applicable"],
      ["hiring-readiness", "not_applicable"],
      ["payroll-remittance", "not_applicable"],
    ]),
  },
  {
    id: "first-hire",
    number: "04",
    title: bi("First employee readiness", "首位员工准备"),
    descriptor: bi(
      "Operating Ontario business · hiring first employee",
      "经营中的安省企业 · 准备招聘首位员工",
    ),
    outcome: bi(
      "A date-driven hiring pack connecting payroll, WSIB, workplace information and remittance reminders.",
      "以日期为驱动，连接Payroll、WSIB、工作场所信息及汇缴提醒。",
    ),
    badge: bi("Hiring milestone", "招聘里程碑"),
    accent: "purple",
    profile: {
      stage: "operating",
      city: "Ontario",
      industry: "services",
      structure: "corporation",
      employees: "hiring",
      revenue: "over_30k",
      imports: false,
      crossProvince: false,
      complexResidency: false,
    },
    tasks: plan([
      ["registration-review", "mandatory"],
      ["permit-scan", "mandatory"],
      ["gst-decision", "mandatory"],
      ["accounting-stack", "mandatory"],
      ["privacy-casl", "mandatory"],
      ["record-policy", "mandatory"],
      ["quarterly-review", "mandatory"],
      ["insurance-review", "mandatory"],
      ["obr-access", "mandatory"],
      ["corporate-records", "mandatory"],
      ["bn-accounts", "mandatory"],
      ["business-banking", "conditional"],
      ["annual-return", "mandatory"],
      ["t2-return", "mandatory"],
      ["t2-balance", "mandatory"],
      ["isc-review", "mandatory"],
      ["gst-return", "conditional"],
      ["import-export", "not_applicable"],
      ["payroll-account", "mandatory"],
      ["hiring-readiness", "mandatory"],
      ["wsib", "conditional"],
      ["posters", "mandatory"],
      ["employment-baseline", "mandatory"],
      ["payroll-remittance", "mandatory"],
    ]),
  },
  {
    id: "complex-residency",
    number: "05",
    title: bi("Complex residency or control", "复杂居住地或控制权"),
    descriptor: bi(
      "All directors or controlling owners may be outside Canada",
      "全部董事或控制人可能位于加拿大境外",
    ),
    outcome: bi(
      "Ontario has no general director-residency requirement. Review is for cross-border ownership, tax, banking and filing facts—not a claim that incorporation is unavailable.",
      "安省没有普遍的董事居留要求。专家审查针对跨境所有权、税务、银行和申报事实，并不表示无法在安省成立公司。",
    ),
    badge: bi("Expert review", "专家审查"),
    accent: "slate",
    boundary: true,
    profile: {
      stage: "planning",
      city: "Ontario",
      industry: "services",
      structure: "undecided",
      employees: "none",
      revenue: "under_30k",
      imports: false,
      crossProvince: true,
      complexResidency: true,
    },
    tasks: plan([
      ["choose-structure", "needs_expert"],
      ["name-search", "needs_expert"],
      ["ontario-registration", "needs_expert"],
      ["permit-scan", "needs_expert"],
      ["gst-decision", "needs_expert"],
      ["accounting-stack", "needs_expert"],
      ["privacy-casl", "needs_expert"],
      ["record-policy", "needs_expert"],
      ["quarterly-review", "needs_expert"],
      ["insurance-review", "needs_expert"],
      ["obr-access", "needs_expert"],
      ["corporate-records", "needs_expert"],
      ["bn-accounts", "needs_expert"],
      ["business-banking", "needs_expert"],
      ["annual-return", "needs_expert"],
      ["t2-return", "needs_expert"],
      ["t2-balance", "needs_expert"],
      ["isc-review", "needs_expert"],
      ["name-renewal", "needs_expert"],
      ["import-export", "not_applicable"],
      ["payroll-account", "not_applicable"],
      ["hiring-readiness", "not_applicable"],
      ["payroll-remittance", "not_applicable"],
    ]),
  },
  {
    id: "regulated-business",
    number: "06",
    title: bi("Regulated or multi-province business", "受监管或跨省复杂业务"),
    descriptor: bi(
      "Industry-specific approval or complex extra-provincial activity",
      "行业特定审批或复杂跨省经营",
    ),
    outcome: bi(
      "Organizes the questions and source-backed tasks to review with a qualified expert without issuing definitive applicability conclusions.",
      "整理需与合格专业人士复核的问题及有来源依据的任务，不输出确定的适用性结论。",
    ),
    badge: bi("Boundary case", "边界案例"),
    accent: "red",
    boundary: true,
    profile: {
      stage: "planning",
      city: "Toronto",
      industry: "regulated",
      structure: "corporation",
      employees: "hiring",
      revenue: "near_30k",
      imports: false,
      crossProvince: true,
      complexResidency: false,
    },
    tasks: plan([
      ["choose-structure", "needs_expert"],
      ["name-search", "needs_expert"],
      ["ontario-registration", "needs_expert"],
      ["permit-scan", "needs_expert"],
      ["gst-decision", "needs_expert"],
      ["accounting-stack", "needs_expert"],
      ["privacy-casl", "needs_expert"],
      ["record-policy", "needs_expert"],
      ["quarterly-review", "needs_expert"],
      ["insurance-review", "needs_expert"],
      ["toronto-check", "needs_expert"],
      ["obr-access", "needs_expert"],
      ["corporate-records", "needs_expert"],
      ["bn-accounts", "needs_expert"],
      ["business-banking", "needs_expert"],
      ["annual-return", "needs_expert"],
      ["t2-return", "needs_expert"],
      ["t2-balance", "needs_expert"],
      ["isc-review", "needs_expert"],
      ["gst-return", "needs_expert"],
      ["import-export", "not_applicable"],
      ["payroll-account", "needs_expert"],
      ["hiring-readiness", "needs_expert"],
      ["wsib", "needs_expert"],
      ["posters", "needs_expert"],
      ["employment-baseline", "needs_expert"],
      ["payroll-remittance", "needs_expert"],
    ]),
  },
];

const providerRecords: Provider[] = [
  {
    id: "official-obr",
    name: "Ontario Business Registry",
    type: "official",
    category: bi("Registration & filings", "注册与申报"),
    description: bi(
      "Official Ontario service for business registrations, incorporations, updates and annual returns.",
      "安省企业注册、成立、变更及年度申报的官方服务。",
    ),
    region: bi("Ontario", "安省"),
    price: bi("Official transaction fees vary", "官方交易费用因类型而异"),
    priceSource: bi(
      "Ontario.ca — verify before filing",
      "Ontario.ca——提交前请核验",
    ),
    verified: "2026-09-04",
    website: "https://www.ontario.ca/page/ontario-business-registry",
    sharedFields: [],
  },
  {
    id: "official-bizpal",
    name: "BizPaL",
    type: "official",
    category: bi("Permit discovery", "许可查询"),
    description: bi(
      "Government permit and licence finder spanning participating federal, provincial and municipal jurisdictions.",
      "覆盖参与的联邦、省和市级辖区的政府许可与牌照查询工具。",
    ),
    region: bi("Canada, including Ontario", "加拿大，包括安省"),
    price: bi("Free to search", "免费查询"),
    priceSource: bi("Official service", "官方服务"),
    verified: "2026-09-04",
    website: "https://ised-isde.canada.ca/site/bizpal/en",
    sharedFields: [],
  },
  {
    id: "northstar-books",
    name: "Northstar Bookkeeping",
    type: "demo_partner",
    category: bi("Bookkeeping", "记账服务"),
    description: bi(
      "Fictional demo provider for monthly bookkeeping setup and milestone support.",
      "用于展示月度记账设置和里程碑支持的虚构服务商。",
    ),
    region: bi("Ontario — remote", "安省——远程服务"),
    price: bi("Illustrative: from CAD 249/month", "示例：CAD 249/月起"),
    priceSource: bi("Demo data — not a quote", "演示数据——并非报价"),
    verified: "2026-09-04",
    website: "#referral",
    sharedFields: [
      bi("Business type", "企业类型"),
      bi("Stage", "经营阶段"),
      bi("Preferred contact email", "首选联系邮箱"),
    ],
    commercialDisclosure: bi(
      "Demo only. A future agreement may compensate Launchpad for a qualified introduction.",
      "仅供演示。未来签署合作协议后，Launchpad可能因有效转介获得报酬。",
    ),
  },
  {
    id: "harbour-risk",
    name: "Harbour Risk Advisory",
    type: "sponsored",
    category: bi("Business insurance", "商业保险"),
    description: bi(
      "Fictional sponsored listing demonstrating a transparent broker handoff.",
      "虚构赞助展示，用于演示透明的保险经纪转介。",
    ),
    region: bi("Ontario", "安省"),
    price: bi("Quote required", "需要报价"),
    priceSource: bi(
      "Provider underwriting — no quote in this demo",
      "由服务商核保——本演示不提供报价",
    ),
    verified: "2026-09-04",
    website: "#referral",
    sharedFields: [
      bi("Industry", "行业"),
      bi("Revenue band", "收入区间"),
      bi("Employee band", "员工区间"),
      bi("Preferred contact email", "首选联系邮箱"),
    ],
    commercialDisclosure: bi(
      "Sponsored demo placement. No real commercial relationship exists in this prototype.",
      "赞助位演示。本原型不存在真实商业合作关系。",
    ),
  },
  {
    id: "maple-counsel",
    name: "Maple Counsel Network",
    type: "independent",
    category: bi("Legal review", "法律审查"),
    description: bi(
      "Fictional independent directory entry for complex structure and contract questions.",
      "用于复杂结构和合同问题的虚构独立目录条目。",
    ),
    region: bi("Ontario", "安省"),
    price: bi(
      "Provider sets engagement terms directly",
      "由服务商直接确定委托条款",
    ),
    priceSource: bi("No price supplied", "未提供价格"),
    verified: "2026-09-04",
    website: "#referral",
    sharedFields: [
      bi("Issue category", "问题类别"),
      bi("Business stage", "经营阶段"),
      bi("Preferred contact email", "首选联系邮箱"),
    ],
  },
];

export const providers: Provider[] = providerRecords.map((provider) => ({
  ...provider,
  verified: "2026-09-04",
}));

export const calendarEvents: CalendarEvent[] = [
  {
    id: "cal-isc",
    month: "NOV",
    day: "12",
    type: "corporate",
    title: bi("Annual ISC record review", "年度ISC记录复核"),
    note: bi(
      "Internal corporate record review; update promptly after known changes.",
      "公司内部记录复核；获悉变更后应及时更新。",
    ),
    sourceId: "isc",
  },
  {
    id: "cal-gst",
    month: "DEC",
    day: "31",
    type: "tax",
    title: bi("GST/HST reporting period ends", "GST/HST申报期结束"),
    note: bi(
      "A reporting-period marker, not the filing deadline. Confirm your assigned frequency.",
      "这是申报期节点，不是提交截止日。请确认分配的申报频率。",
    ),
    sourceId: "gst-filing",
  },
  {
    id: "cal-payroll",
    month: "JAN",
    day: "15",
    type: "payroll",
    title: bi("Illustrative payroll remittance", "Payroll汇缴示例"),
    note: bi(
      "New regular remitters are often due on the 15th; follow the frequency assigned by CRA.",
      "普通新汇缴人通常在15日到期；应以CRA分配频率为准。",
    ),
    sourceId: "payroll-remit",
  },
  {
    id: "cal-t2-balance",
    month: "JAN",
    day: "31",
    type: "tax",
    title: bi("Corporation tax balance review", "公司税款余额复核"),
    note: bi(
      "Payment timing is separate from the T2 filing date and may be earlier. Confirm the two- or three-month rule for your facts.",
      "付款时间与T2申报日期分开，且可能更早。请结合实际情况确认两个月或三个月规则。",
    ),
    sourceId: "t2-balance",
  },
  {
    id: "cal-annual",
    month: "APR",
    day: "30",
    type: "corporate",
    title: bi("Ontario corporate annual return", "安省公司年度申报"),
    note: bi(
      "Registry filing — not a tax return. Illustrative deadline for the demo's October 31 fiscal year-end.",
      "公司注册处申报——并非税务申报。示例按10月31日财年末计算截止日。",
    ),
    sourceId: "obr",
  },
  {
    id: "cal-t2",
    month: "APR",
    day: "30",
    type: "tax",
    title: bi("T2 corporation return", "T2公司所得税申报"),
    note: bi(
      "Illustrative six-month filing date. Tax balance timing is a separate calculation.",
      "示例为六个月申报日；税款余额到期时间需另行计算。",
    ),
    sourceId: "t2-filing",
  },
  {
    id: "cal-renew",
    month: "JUN",
    day: "18",
    type: "permit",
    title: bi("Permit, insurance and domain review", "许可、保险和域名复核"),
    note: bi(
      "Workspace reminder only. Renew each item with its issuer or provider.",
      "仅为工作台提醒。各项目应向原签发方或服务商续期。",
    ),
    sourceId: "bizpal",
  },
];

export const assistantPrompts = [
  {
    id: "annual-vs-t2",
    question: bi(
      "What is the difference between an annual return and a T2?",
      "公司年度申报和T2有什么区别？",
    ),
    answer: bi(
      "An Ontario corporate annual return updates registry information. A T2 is the corporation income tax return filed with CRA. Completing one does not complete the other.",
      "安省公司年度申报用于更新注册处信息；T2是向CRA提交的公司所得税申报。完成其中一项并不代表完成另一项。",
    ),
    sourceIds: ["obr", "t2"],
  },
  {
    id: "gst-threshold",
    question: bi(
      "Do I need GST/HST registration at CAD 30,000?",
      "收入达到CAD 30,000就必须注册GST/HST吗？",
    ),
    answer: bi(
      "The general small-supplier test considers taxable worldwide supplies and timing. Exceeding CAD 30,000 in one calendar quarter differs from exceeding it over four consecutive quarters. Review the official CRA rule for your facts.",
      "一般小供应商测试会考虑全球应税销售及发生时间。在单个日历季度超过CAD 30,000与连续四个季度累计超过时，规则不同。请结合实际情况查看CRA官方规则。",
    ),
    sourceIds: ["gst"],
  },
  {
    id: "sole-registration",
    question: bi(
      "Does every sole proprietor register a business name?",
      "每个个体经营者都要注册企业名称吗？",
    ),
    answer: bi(
      "Registration depends on how you operate and the name you use. Ontario notes that some sole proprietors operating only under their own legal name may not need a business-name registration.",
      "是否注册取决于经营方式和使用的名称。安省说明，仅使用本人法定姓名经营的部分个体经营者可能无需注册企业名称。",
    ),
    sourceIds: ["on-register"],
  },
  {
    id: "licence",
    question: bi(
      "How do I know which permits apply in Toronto?",
      "如何判断在多伦多需要哪些许可？",
    ),
    answer: bi(
      "Start with your exact activity and operating address. Use BizPaL and the City of Toronto business-regulation pages, then confirm any zoning or sector-specific requirements before committing to premises.",
      "先明确具体经营活动和地址。使用BizPaL及多伦多市商业监管页面，并在确定场所前核实分区和行业特定要求。",
    ),
    sourceIds: ["bizpal", "toronto-permits"],
  },
];

export const getTask = (id: string) => tasks.find((task) => task.id === id);
export const getScenario = (id: string) =>
  scenarios.find((scenario) => scenario.id === id);
export const getSource = (id: string) =>
  sources.find((source) => source.id === id);
